### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by SheepCommander** [yuwui/powercord-greentext#3]
Raw Message:
```md
>Flirts with ~~chicken~~ anime girl
>Attempts to groom the Official Sonic account which in turn sends **"Keep your *Kentucky Fried* fetish away from me"**
>The espanol KFC branch has no idea what's happening
```

![image](https://user-images.githubusercontent.com/66646514/144730615-b6afe7c7-f974-48c9-bf97-a40588e013d3.png)
![image](https://user-images.githubusercontent.com/66646514/144730618-81aed7ab-e2e7-41ed-9458-b661c5535c3a.png)

**Comment by na-2n** [comment]
i'm aware of this issue, i'll see if i can do something about it tomorrow

**Comment by SheepCommander** [comment]
Thanks!

**Comment by na-2n** [comment]
fixed in latest commit
