### ISSUE TITLE
[Bug Report] Newlines sometimes not respected?

### ISSUE THREAD

**Issue by SheepCommander** [yuwui/powercord-greentext#5]
Without powercord-greentext

![image](https://user-images.githubusercontent.com/66646514/147802159-5fd27184-200f-46d7-88d9-a2ac7ff75429.png)

With powercord-greentext

![image](https://user-images.githubusercontent.com/66646514/147802178-67b91a4c-00cd-4d37-89dc-f499094b75a4.png)

Raw message
```
>Picture of toilet paper roll ontop of the stand instead of actually inside
Lawful Evil
"Replacing toilet paper is basic curtesy but I don't have enough damn to give to do it correctly"
```

**Comment by na-2n** [comment]
should be fixed in latest commit!

**Comment by SheepCommander** [comment]
Nice!
